
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-site
  namespace: ns-test-site
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: test-site
        image: spardoks/devops-template-tasks-site:0.1
        resources:
          requests:
            cpu: "1"
            memory: "200Mi"
          limits:
            cpu: "2"
            memory: "400Mi"
        ports:
        - containerPort: 80
